# Generated by Django 3.0.8 on 2020-08-13 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commnet_author',
            new_name='comment_author',
        ),
    ]
